# Generated by Django 5.2.1 on 2025-05-30 18:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('municipio', models.CharField(max_length=50)),
                ('dpto', models.CharField(max_length=60)),
                ('disposicion', models.CharField(max_length=60)),
                ('cod_dane', models.CharField(max_length=5)),
                ('created_date', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('gid', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=254)),
                ('departamen', models.CharField(max_length=254)),
                ('municipio', models.CharField(max_length=254)),
            ],
        ),
    ]
