# Generated by Django 5.2.1 on 2025-05-30 19:26

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='cod_dane',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=60),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='disposicion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='dpto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
