# Generated by Django 5.2.1 on 2025-05-30 19:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_municipio_cod_dane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='departamen',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='gid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='municipio',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombre',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
