# Generated by Django 5.2.1 on 2025-05-30 21:01

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('dpto', models.CharField(blank=True, max_length=60, null=True)),
                ('disposicion', models.CharField(blank=True, max_length=60, null=True)),
                ('cod_dane', models.CharField(blank=True, max_length=60, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('gid', models.BigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=254, null=True)),
                ('departamen', models.CharField(blank=True, max_length=254, null=True)),
                ('municipio', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
