"""
Django settings for prueba_tecnica project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import sys

# ===================================
# Base Directory
# ===================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ===================================
# Security Settings
# ===================================
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = []

# ===================================
# Application Definition
# ===================================
INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.postgres',

    # Third-party apps
    'rest_framework',
    'rest_framework_gis',
    'rest_framework_simplejwt',

    # Local apps
    'prueba_tecnica',
    'core',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prueba_tecnica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prueba_tecnica.wsgi.application'

# ===================================
# Database Configuration
# ===================================
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# ===================================
# Password Validation
# ===================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ===================================
# Internationalization
# ===================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ===================================
# Static Files
# ===================================
STATIC_URL = 'static/'

# ===================================
# Default Primary Key Field Type
# ===================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===================================
# QGIS & GDAL Setup
# ===================================
QGIS_PATH = r"C:\Program Files\QGIS 3.34.13"
PYTHON_SITEPACKAGES = QGIS_PATH + r"\apps\Python312\Lib\site-packages"
GDAL_DLL_PATH = QGIS_PATH + r"\bin\gdal310.dll"

os.environ['PATH'] = (
    QGIS_PATH + r"\bin;" +
    QGIS_PATH + r"\apps\Qt5\bin;" +
    os.environ['PATH']
)
os.environ['GDAL_LIBRARY_PATH'] = GDAL_DLL_PATH
sys.path.append(PYTHON_SITEPACKAGES)

# ===================================
# Django REST Framework Configuration
# ===================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}